apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-produsent-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  ingresses:
    - https://ag-notifikasjon-produsent-api.intern.dev.nav.no/
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 1
    max: 2
  prometheus:
    enabled: true
    path: /internal/metrics
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-f1-micro
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: produsent-model
            envVarPrefix: DB
  accessPolicy:
    outbound:
      external:
        - host: fakedings.intern.dev.nav.no
        - host: tt02.altinn.no
    inbound:
      rules:
        - application: notifikasjon-test-produsent
        - application: notifikasjon-test-produsent-v2

        - application: tiltak-refusjon-api
          namespace: arbeidsgiver
          cluster: dev-gcp

        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: dev-fss

        - application: tiltak-notifikasjon
          namespace: team-tiltak
          cluster: dev-gcp

        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-fss

        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-gcp

        - application: permitteringsmelding-notifikasjon
          namespace: permittering-og-nedbemanning
          cluster: dev-gcp

        - application: fritakagp
          namespace: helsearbeidsgiver
          cluster: dev-gcp

        - application: im-notifikasjon
          namespace: helsearbeidsgiver
          cluster: dev-gcp

        - application: toi-arbeidsgiver-notifikasjon
          namespace: toi
          cluster: dev-gcp
          
        - application: saas-proxy
          namespace: teamcrm
          cluster: dev-gcp

        - application: salesforce
          namespace: teamcrm
          cluster: dev-external

        - application: yrkesskade-melding-mottak
          namespace: yrkesskade
          cluster: dev-gcp

        - application: ftinntektsmelding
          namespace: teamforeldrepenger
          cluster: dev-gcp

        - application: fpinntektsmelding
          namespace: teamforeldrepenger
          cluster: dev-gcp

        - application: k9-inntektsmelding
          namespace: k9saksbehandling
          cluster: dev-gcp

  envFrom:
    - secret: notifikasjon-produsent-api-secrets
